language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t mydocker-image/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mydocker-image/docker-react npm run test